### ISSUE TITLE
wget

### ISSUE THREAD

**Issue by liwenjielongren** [YoungXIAO13/FewShotViewpoint#1]
![image](https://user-images.githubusercontent.com/52265815/90208619-d0fdd200-de1b-11ea-898d-cf425e2f6762.png)

**Comment by YoungXIAO13** [comment]
Hi,
The cmd has been updated, you can try it again.

**Comment by YoungXIAO13** [comment]
Hi,
The cmd has been updated, you can try it again.

**Comment by liwenjielongren** [comment]
I try again，It also connect timed out

**Comment by YoungXIAO13** [comment]
You can now download it from BaiduPan: https://pan.baidu.com/s/1FMYdi6LRhRir_QdpEbpUgg (code: no8t)

**Comment by liwenjielongren** [comment]
ok，thank you

**Comment by liwenjielongren** [comment]
![image](https://user-images.githubusercontent.com/52265815/90329286-f9313080-dfd5-11ea-8901-858786460a8e.png)
Sorry to disturb you，What is the reason for this problem？my path is right

**Comment by YoungXIAO13** [comment]
Sorry for the late reply, could you check the data preparation is completed successfully, e.g. the point clouds path and annotation txt file are set correctly?
