### ISSUE TITLE
Can't download the point clouds for this dataset

### ISSUE THREAD

**Issue by lxzy-ai** [YoungXIAO13/FewShotViewpoint#2]
> download_object3d.sh  #22
```
wget --header 'Host: uc23d47b3615cc6557d59b6a3ae5.dl.dropboxusercontent.com' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-US,en;q=0.5' --referer 'https://www.dropbox.com/' --header 'Upgrade-Insecure-Requests: 1' 'https://uc23d47b3615cc6557d59b6a3ae5.dl.dropboxusercontent.com/cd/0/get/A8GKqmoG-OuJ_z0eMpz12RGIfC8UmGoK1_gkgL3tskQz4WydJr50I_SqcdywnzBoca01TpfUAf6rCXlifu6ss6MqKD2XjA1ooD90Ge9qeQNtTo1Nl-q7kXWrCHkKy0lenLM/file#' --output-document 'ObjectNet3DPointclouds.zip'
```
![image](https://user-images.githubusercontent.com/20589497/92574815-2c579e80-f2ba-11ea-9814-34530a3630d8.png)
![image](https://user-images.githubusercontent.com/20589497/92574845-38436080-f2ba-11ea-83ed-796a75d87738.png)
**I request you to offer Google drive links of point clouds data of ObjectNet3D and Pascal3D dataset**
thanks a lot

**Comment by YoungXIAO13** [comment]
Hi, 
You can follow the instructions in repo [PoseFromShape](https://github.com/YoungXIAO13/PoseFromShape#updates-2020-july) to get the point clouds of Pascal3D and ObjectNet3D

**Comment by lxzy-ai** [comment]
ok,thanks alot
