### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by tirilsu** [YoungXIAO13/FewShotViewpoint#3]
Hi,

Is it possible to run the code as a demo on my own images? Can you please provide a guide on how to do this?

Thank you!

**Comment by YoungXIAO13** [comment]
Hi @tirilsu ,

Thanks for your interests! I've updated a ``demo.py`` to the repo and you can see how to use it [here](https://github.com/YoungXIAO13/FewShotViewpoint#demo).

**Comment by tirilsu** [comment]
Thank you very much! 

Will the same script work for your method on FewShotDetection?

**Comment by YoungXIAO13** [comment]
I suppose you want the [all_box](https://github.com/YoungXIAO13/FewShotDetection/blob/a526e64db04f77c0514cd680b3559789114b0186/test.py#L368) in detection ?
Or you can just use ``--vis`` command to visualize the high-confidence detection results.

For more details on the detection part, you can refer to the [demo.py](https://github.com/jwyang/faster-rcnn.pytorch/blob/master/demo.py) from the original faster-rcnn.pytorch repo.

**Comment by tirilsu** [comment]
Yes that's right, I figured it out now. Thank you!

**Comment by tirilsu** [comment]
Is the --test_cls {test_class_name} used for the demo supposed to refer to a key in the mean_class_attentions.pkl file? Or does it have anything to do with the pointcloud files?

**Comment by YoungXIAO13** [comment]
This represents the class of the test object, which should be one of the training classes included in the keys of ``mean_class_attentions.pkl``. 

Point clouds are only used during training to optimise the weights of class feature extraction module, then ``mean_class_attentions.pkl`` is generated by averaging point cloud features for each class.
